version: '3'
services:
  db:
    image: postgres:10-alpine
    env_file:
      - .envfile
    environment:
      - POSTGRES_USER=graph
      - POSTGRES_PASSWORD=graph
      - POSTGRES_DB=graph
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 8000
  web:
    build:
      context: ./graph
      dockerfile: graph/development.Dockerfile
    image: trojsten-graph
    env_file:
      - .envfile
    environment:
      - DJANGO_SETTINGS_MODULE=graph.settings.development
    ports:
      - "8000:8000"
    volumes:
      - ./graph/:/usr/src/graph/
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
