version: '3'
services:
  graph-db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=graph
      - POSTGRES_DB=graph
    ports:
      - "5432:5432"
  graph2.0:
    build: .
    image: trojsten-graph
    environment:
      - PGHOST=graph-db
    ports:
      - "8000:8000"
    volumes:
      - .:/graph
    depends_on:
      - graph-db
    command: python3 manage.py runserver 0.0.0.0:8000
    networks:
      default:
        aliases:
          - www.trojsten-graph.top
